#!/bin/sh
#xampp manager
#writen by --lijunqi
case "$1" in
#start xampp service
"1")
/opt/lampp/lampp start;;
#stop xampp service
"2")
/opt/lampp/lampp stop;;
#xampp gui
"3")
cd /opt/lampp
./manager-linux-x64.run;;
esac
